export type WorkerRunOnceResponse = {
  claimed: boolean;
  message: string;
  execution_mode: string | null;
  verification_mode: string | null;
  verification_template: string | null;
  verification_summary: string | null;
  failure_category: string | null;
  quality_gate_passed: boolean | null;
  route_reason: string | null;
  routing_score: number | null;
  routing_score_breakdown: Array<{
    code: string;
    label: string;
    score: number;
    detail: string;
  }>;
  owner_role_code: string | null;
  upstream_role_code: string | null;
  downstream_role_code: string | null;
  handoff_reason: string | null;
  dispatch_status: string | null;
  project_memory_enabled: boolean | null;
  project_memory_query_text: string | null;
  project_memory_item_count: number | null;
  project_memory_context_summary: string | null;
  result_summary: string | null;
  context_summary: string | null;
  model_name: string | null;
  model_tier: string | null;
  selected_skill_codes: string[];
  selected_skill_names: string[];
  strategy_code: string | null;
  strategy_summary: string | null;
  role_model_policy_source: string | null;
  role_model_policy_desired_tier: string | null;
  role_model_policy_adjusted_tier: string | null;
  role_model_policy_final_tier: string | null;
  role_model_policy_stage_override_applied: boolean;
  task_id: string | null;
  task_title: string | null;
  task_status: string | null;
  run_id: string | null;
  run_status: string | null;
  run_created_at: string | null;
  run_finished_at: string | null;
  provider_key: string | null;
  prompt_template_key: string | null;
  prompt_template_version: string | null;
  prompt_char_count: number | null;
  token_accounting_mode: string | null;
  provider_receipt_id: string | null;
  total_tokens: number | null;
  token_pricing_source: string | null;
  prompt_tokens: number | null;
  completion_tokens: number | null;
  estimated_cost: number | null;
  log_path: string | null;
  agent_session_id: string | null;
  agent_session_status: string | null;
  agent_review_status: string | null;
  agent_current_phase: string | null;
  agent_type: string | null;
  runtime_type: string | null;
  runtime_handle_id: string | null;
  coding_status: string | null;
  activity_state: string | null;
  branch_name: string | null;
  workspace_type: string | null;
  workspace_path: string | null;
  workspace_clean: boolean | null;
  last_workspace_error: string | null;
  workspace_context_ready: boolean | null;
  workspace_context_source: string | null;
  workspace_context_reason_code: string | null;
  workspace_context_path: string | null;
  workspace_context_resolved_path: string | null;
  workspace_context_uses_agent_workspace: boolean | null;
  workspace_context_changes_cwd: boolean | null;
  workspace_context_runs_git: boolean | null;
  workspace_context_runs_write_git: boolean | null;
  workspace_context_launches_runtime: boolean | null;
  runtime_launch_dry_run_ready: boolean | null;
  runtime_launch_dry_run_source: string | null;
  runtime_launch_dry_run_reason_code: string | null;
  runtime_launch_dry_run_session_id: string | null;
  runtime_launch_dry_run_agent_type: string | null;
  runtime_launch_dry_run_runtime_type: string | null;
  runtime_launch_dry_run_workspace_path: string | null;
  runtime_launch_dry_run_resolved_workspace_path: string | null;
  runtime_launch_dry_run_launch_cwd_preview: string | null;
  runtime_launch_dry_run_launch_command_preview: string | null;
  runtime_launch_dry_run_uses_agent_workspace: boolean | null;
  runtime_launch_dry_run_command_preview_uses_workspace: boolean | null;
  runtime_launch_dry_run_execution_enabled: boolean | null;
  runtime_launch_dry_run_changes_cwd: boolean | null;
  runtime_launch_dry_run_runs_command: boolean | null;
  runtime_launch_dry_run_runs_git: boolean | null;
  runtime_launch_dry_run_runs_write_git: boolean | null;
  runtime_launch_dry_run_launches_runtime: boolean | null;
  runtime_launch_gate_ready: boolean | null;
  runtime_launch_gate_gates_passed: string[];
  runtime_launch_gate_gates_failed: string[];
  runtime_launch_gate_blocking_reason_code: string | null;
  runtime_launch_gate_blocking_summary: string | null;
  runtime_launch_gate_changes_process_cwd: boolean | null;
  runtime_launch_gate_runs_real_command: boolean | null;
  runtime_launch_gate_runs_git: boolean | null;
  runtime_launch_gate_runs_write_git: boolean | null;
  runtime_launch_gate_launches_ai_runtime: boolean | null;
  runtime_launch_gate_execution_enabled: boolean | null;
  runtime_lifecycle_snapshot: {
    ready: boolean;
    source: string;
    state: string;
    reason: string;
    reason_code: string | null;
    summary: string;
    session_id: string | null;
    agent_type: string | null;
    runtime_type: string | null;
    adapter_kind: string | null;
    workspace_path: string | null;
    resolved_workspace_path: string | null;
    launch_cwd_preview: string | null;
    runtime_handle_id: string | null;
    gates_passed: string[];
    gates_failed: string[];
    blocking_reason_code: string | null;
    blocking_summary: string | null;
    launch_requested: boolean;
    fake_launch_started: boolean;
    real_runtime_started: boolean;
    runtime_probe_started: boolean;
    probe_state: string | null;
    probe_reason_code: string | null;
    probe_error_summary: string | null;
    execution_enabled: boolean;
    changes_process_cwd: boolean;
    runs_real_command: boolean;
    runs_git: boolean;
    runs_write_git: boolean;
    launches_ai_runtime: boolean;
  } | null;
  worktree_safe_command_proof_ready: boolean | null;
  worktree_safe_command_proof_reason_code: string | null;
  worktree_safe_command_proof_observed_pwd: string | null;
  worktree_safe_command_proof_pwd_matches_workspace_path: boolean | null;
};

export type WorkerSlot = {
  slot_id: number;
  state: string;
  worker_name: string | null;
  task_id: string | null;
  task_title: string | null;
  run_id: string | null;
  acquired_at: string | null;
  last_task_id: string | null;
  last_task_title: string | null;
  last_run_id: string | null;
  last_released_at: string | null;
};

export type WorkerSlotSnapshot = {
  max_concurrent_workers: number;
  running_slots: number;
  idle_slots: number;
  slots: WorkerSlot[];
};

export type WorkerPoolRunResponse = {
  requested_workers: number;
  launched_workers: number;
  claimed_runs: number;
  idle_workers: number;
  results: WorkerRunOnceResponse[];
  slot_snapshot: WorkerSlotSnapshot;
};

export type TaskRetryResponse = {
  message: string;
  task_id: string;
  task_title: string;
  previous_status: string;
  current_status: string;
  updated_at: string;
};

export type TaskStateActionResponse = {
  message: string;
  task_id: string;
  task_title: string;
  previous_status: string;
  current_status: string;
  human_status: string;
  paused_reason: string | null;
  updated_at: string;
};
