export type WorkerRunOnceResponse = {
  claimed: boolean;
  message: string;
  execution_mode: string | null;
  verification_mode: string | null;
  verification_template: string | null;
  verification_summary: string | null;
  failure_category: string | null;
  quality_gate_passed: boolean | null;
  route_reason: string | null;
  routing_score: number | null;
  routing_score_breakdown: Array<{
    code: string;
    label: string;
    score: number;
    detail: string;
  }>;
  owner_role_code: string | null;
  upstream_role_code: string | null;
  downstream_role_code: string | null;
  handoff_reason: string | null;
  dispatch_status: string | null;
  project_memory_enabled: boolean | null;
  project_memory_query_text: string | null;
  project_memory_item_count: number | null;
  project_memory_context_summary: string | null;
  result_summary: string | null;
  context_summary: string | null;
  model_name: string | null;
  model_tier: string | null;
  selected_skill_codes: string[];
  selected_skill_names: string[];
  strategy_code: string | null;
  strategy_summary: string | null;
  role_model_policy_source: string | null;
  role_model_policy_desired_tier: string | null;
  role_model_policy_adjusted_tier: string | null;
  role_model_policy_final_tier: string | null;
  role_model_policy_stage_override_applied: boolean;
  task_id: string | null;
  task_title: string | null;
  task_status: string | null;
  run_id: string | null;
  run_status: string | null;
  run_created_at: string | null;
  run_finished_at: string | null;
  provider_key: string | null;
  prompt_template_key: string | null;
  prompt_template_version: string | null;
  prompt_char_count: number | null;
  token_accounting_mode: string | null;
  provider_receipt_id: string | null;
  total_tokens: number | null;
  token_pricing_source: string | null;
  prompt_tokens: number | null;
  completion_tokens: number | null;
  estimated_cost: number | null;
  log_path: string | null;
  agent_session_id: string | null;
  agent_session_status: string | null;
  agent_review_status: string | null;
  agent_current_phase: string | null;
  agent_type: string | null;
  runtime_type: string | null;
  runtime_handle_id: string | null;
  coding_status: string | null;
  activity_state: string | null;
  branch_name: string | null;
  workspace_type: string | null;
  workspace_path: string | null;
  workspace_clean: boolean | null;
  last_workspace_error: string | null;
  workspace_context_ready: boolean | null;
  workspace_context_source: string | null;
  workspace_context_reason_code: string | null;
  workspace_context_path: string | null;
  workspace_context_resolved_path: string | null;
  workspace_context_uses_agent_workspace: boolean | null;
  workspace_context_changes_cwd: boolean | null;
  workspace_context_runs_git: boolean | null;
  workspace_context_runs_write_git: boolean | null;
  workspace_context_launches_runtime: boolean | null;
  runtime_launch_dry_run_ready: boolean | null;
  runtime_launch_dry_run_source: string | null;
  runtime_launch_dry_run_reason_code: string | null;
  runtime_launch_dry_run_session_id: string | null;
  runtime_launch_dry_run_agent_type: string | null;
  runtime_launch_dry_run_runtime_type: string | null;
  runtime_launch_dry_run_workspace_path: string | null;
  runtime_launch_dry_run_resolved_workspace_path: string | null;
  runtime_launch_dry_run_launch_cwd_preview: string | null;
  runtime_launch_dry_run_launch_command_preview: string | null;
  runtime_launch_dry_run_uses_agent_workspace: boolean | null;
  runtime_launch_dry_run_command_preview_uses_workspace: boolean | null;
  runtime_launch_dry_run_execution_enabled: boolean | null;
  runtime_launch_dry_run_changes_cwd: boolean | null;
  runtime_launch_dry_run_runs_command: boolean | null;
  runtime_launch_dry_run_runs_git: boolean | null;
  runtime_launch_dry_run_runs_write_git: boolean | null;
  runtime_launch_dry_run_launches_runtime: boolean | null;
  runtime_launch_gate_ready: boolean | null;
  runtime_launch_gate_gates_passed: string[];
  runtime_launch_gate_gates_failed: string[];
  runtime_launch_gate_blocking_reason_code: string | null;
  runtime_launch_gate_blocking_summary: string | null;
  runtime_launch_gate_changes_process_cwd: boolean | null;
  runtime_launch_gate_runs_real_command: boolean | null;
  runtime_launch_gate_runs_git: boolean | null;
  runtime_launch_gate_runs_write_git: boolean | null;
  runtime_launch_gate_launches_ai_runtime: boolean | null;
  runtime_launch_gate_execution_enabled: boolean | null;
  runtime_lifecycle_snapshot: {
    ready: boolean;
    source: string;
    state: string;
    reason: string;
    reason_code: string | null;
    summary: string;
    session_id: string | null;
    agent_type: string | null;
    runtime_type: string | null;
    adapter_kind: string | null;
    workspace_path: string | null;
    resolved_workspace_path: string | null;
    launch_cwd_preview: string | null;
    runtime_handle_id: string | null;
    gates_passed: string[];
    gates_failed: string[];
    blocking_reason_code: string | null;
    blocking_summary: string | null;
    launch_requested: boolean;
    fake_launch_started: boolean;
    real_runtime_started: boolean;
    runtime_probe_started: boolean;
    probe_state: string | null;
    probe_reason_code: string | null;
    probe_error_summary: string | null;
    execution_enabled: boolean;
    changes_process_cwd: boolean;
    runs_real_command: boolean;
    runs_git: boolean;
    runs_write_git: boolean;
    launches_ai_runtime: boolean;
  } | null;
  worktree_safe_command_proof_ready: boolean | null;
  worktree_safe_command_proof_reason_code: string | null;
  worktree_safe_command_proof_observed_pwd: string | null;
  worktree_safe_command_proof_pwd_matches_workspace_path: boolean | null;
  git_diff_dry_run_ready: boolean | null;
  git_diff_dry_run_source: string | null;
  git_diff_dry_run_reason_code: string | null;
  git_diff_dry_run_worktree_path: string | null;
  git_diff_dry_run_has_changes: boolean | null;
  git_diff_dry_run_changed_files_count: number | null;
  git_diff_dry_run_changed_files: string[];
  git_diff_dry_run_added_files: string[];
  git_diff_dry_run_modified_files: string[];
  git_diff_dry_run_deleted_files: string[];
  git_diff_dry_run_renamed_files: string[];
  git_diff_dry_run_status_summary_cn: string | null;
  git_diff_dry_run_diff_stat: string | null;
  git_diff_dry_run_diff_shortstat: string | null;
  git_diff_dry_run_branch_name: string | null;
  git_diff_dry_run_compare_branch: string | null;
  git_diff_dry_run_command: string | null;
  git_diff_dry_run_peek_command: string | null;
  git_diff_dry_run_danger_commands_applied: boolean | null;
  git_diff_dry_run_runs_git: boolean | null;
  git_diff_dry_run_runs_write_git: boolean | null;
  git_diff_dry_run_git_add_triggered: boolean | null;
  git_diff_dry_run_git_commit_triggered: boolean | null;
  git_diff_dry_run_git_push_triggered: boolean | null;
  git_diff_dry_run_pr_opened: boolean | null;
  git_diff_dry_run_ci_triggered: boolean | null;
  git_diff_dry_run_execution_enabled: boolean | null;
  git_operation_dry_run_ready: boolean | null;
  git_operation_dry_run_source: string | null;
  git_operation_dry_run_reason_code: string | null;
  git_operation_dry_run_session_id: string | null;
  git_operation_dry_run_project_id: string | null;
  git_operation_dry_run_task_id: string | null;
  git_operation_dry_run_run_id: string | null;
  git_operation_dry_run_worktree_path: string | null;
  git_operation_dry_run_branch_name: string | null;
  git_operation_dry_run_changed_files_count: number | null;
  git_operation_dry_run_changed_files: string[];
  git_operation_dry_run_added_files: string[];
  git_operation_dry_run_modified_files: string[];
  git_operation_dry_run_deleted_files: string[];
  git_operation_dry_run_renamed_files: string[];
  git_operation_dry_run_proposed_operation: string | null;
  git_operation_dry_run_proposed_steps: string[];
  git_operation_dry_run_proposed_commit_message: string | null;
  git_operation_dry_run_proposed_pr_title: string | null;
  git_operation_dry_run_proposed_pr_body: string | null;
  git_operation_dry_run_user_confirmation_required: boolean | null;
  git_operation_dry_run_human_approval_required: boolean | null;
  git_operation_dry_run_feature_flag_required: boolean | null;
  git_operation_dry_run_summary_cn: string | null;
  git_operation_dry_run_runs_git: boolean | null;
  git_operation_dry_run_runs_write_git: boolean | null;
  git_operation_dry_run_git_add_triggered: boolean | null;
  git_operation_dry_run_git_commit_triggered: boolean | null;
  git_operation_dry_run_git_push_triggered: boolean | null;
  git_operation_dry_run_pr_opened: boolean | null;
  git_operation_dry_run_ci_triggered: boolean | null;
  git_operation_dry_run_execution_enabled: boolean | null;
  git_operation_dry_run_operation_applied: boolean | null;
  git_operation_dry_run_approval_granted: boolean | null;
  delivery_gate_evidence_ready: boolean | null;
  delivery_gate_evidence_source: string | null;
  delivery_gate_evidence_reason_code: string | null;
  delivery_gate_evidence_session_id: string | null;
  delivery_gate_evidence_project_id: string | null;
  delivery_gate_evidence_task_id: string | null;
  delivery_gate_evidence_run_id: string | null;
  delivery_gate_evidence_worktree_path: string | null;
  delivery_gate_evidence_branch_name: string | null;
  delivery_gate_evidence_proposed_operation: string | null;
  delivery_gate_evidence_changed_files_count: number | null;
  delivery_gate_evidence_changed_files: string[];
  delivery_gate_evidence_next_required_action: string | null;
  delivery_gate_evidence_user_confirmation_required: boolean | null;
  delivery_gate_evidence_human_approval_required: boolean | null;
  delivery_gate_evidence_delivery_audit_event_present: boolean | null;
  delivery_gate_evidence_delivery_audit_event_type: string | null;
  delivery_gate_evidence_delivery_audit_event_ready: boolean | null;
  delivery_gate_evidence_summary_cn: string | null;
  delivery_gate_evidence_satisfied_conditions: string[];
  delivery_gate_evidence_blocking_reasons: string[];
  delivery_gate_evidence_runs_git: boolean | null;
  delivery_gate_evidence_runs_write_git: boolean | null;
  delivery_gate_evidence_git_add_triggered: boolean | null;
  delivery_gate_evidence_git_commit_triggered: boolean | null;
  delivery_gate_evidence_git_push_triggered: boolean | null;
  delivery_gate_evidence_pr_opened: boolean | null;
  delivery_gate_evidence_ci_triggered: boolean | null;
  delivery_gate_evidence_execution_enabled: boolean | null;
  delivery_gate_evidence_operation_applied: boolean | null;
  delivery_gate_evidence_approval_granted: boolean | null;
  delivery_gate_evidence_gate_allows_write: boolean | null;
  delivery_gate_evidence_gate_allows_user_confirmation: boolean | null;
  failure_recovery_decision: WorkerFailureRecoveryDecision | null;
  agent_dispatch_decision: WorkerAgentDispatchDecision | null;
};

export type WorkerFailureRecoveryDecision = {
  source: string;
  version: string;
  failure_category: string;
  reason_code: string | null;
  recoverable: boolean;
  retry_allowed: boolean;
  recommended_owner: string;
  recommended_owner_label_cn: string;
  next_action: string;
  next_action_label_cn: string;
  next_instruction_kind: string;
  next_instruction_kind_label_cn: string;
  next_instruction_draft_required: boolean;
  next_instruction_draft: string | null;
  requires_human_decision: boolean;
  human_decision_reason: string | null;
  user_visible_summary_cn: string;
  audit_event_type: string;
  rule_codes: string[];
  safety: WorkerFailureRecoveryDecisionSafety;
};

export type WorkerFailureRecoveryDecisionSafety = {
  runs_git: boolean;
  runs_write_git: boolean;
  git_add_triggered: boolean;
  git_commit_triggered: boolean;
  git_push_triggered: boolean;
  pr_opened: boolean;
  merge_triggered: boolean;
  branch_deleted: boolean;
  git_reset_triggered: boolean;
  git_checkout_triggered: boolean;
  git_switch_triggered: boolean;
  git_stash_triggered: boolean;
  git_rebase_triggered: boolean;
  git_tag_triggered: boolean;
  ci_triggered: boolean;
  execution_enabled: boolean;
  worker_dispatch_triggered: boolean;
  api_response_exposed: boolean;
  agent_message_written: boolean;
  task_created: boolean;
  retry_triggered: boolean;
};

export type WorkerAgentDispatchDecision = {
  source: string;
  version: string;
  dispatch_decision_id: string;
  source_failure_recovery_decision_id: string | null;
  source_run_id: string | null;
  source_task_id: string | null;
  recommended_agent: string;
  recommended_agent_label_cn: string;
  dispatch_status: string;
  dispatch_status_label_cn: string;
  dispatch_reason_code: string;
  dispatch_reason_cn: string;
  instruction_kind: string;
  instruction_kind_label_cn: string;
  instruction_draft: string | null;
  evidence_refs: string[];
  audit_event_type: string;
  created_at: string;
  created_by: string;
  api_response_exposed: boolean;
  safety: WorkerAgentDispatchDecisionSafety;
};

export type WorkerAgentDispatchDecisionSafety = WorkerFailureRecoveryDecisionSafety & {
  auto_dispatch_triggered: boolean;
};

export type DeliveryHumanApprovalRequest = {
  run_id: string;
  approval_requested_action: "approve_git_add_commit_preview";
  approval_scope: "git_add_commit_preview";
  approval_confirmation_text: string;
  approval_client_request_id: string;
  approval_expires_at: string;
  expected_changed_files: string[];
  expected_proposed_commit_message: string;
};

export type DeliveryHumanApprovalResponse = {
  ready: boolean;
  reason_code: string | null;
  summary_cn: string;
  source: string;
  run_id: string;
  task_id: string;
  project_id: string;
  session_id: string;
  approval_required: boolean;
  approval_granted: boolean;
  approval_id: string | null;
  approved_by: string | null;
  approved_by_display_name: string | null;
  approval_scope: string | null;
  approval_requested_action: string | null;
  approval_client_request_id: string | null;
  approval_created_at: string | null;
  approval_expires_at: string | null;
  approval_applied: boolean;
  approval_revoked: boolean;
  approval_confirmation_fingerprint: string | null;
  operation_dry_run_ready: boolean | null;
  delivery_gate_evidence_ready: boolean | null;
  delivery_gate_allows_user_confirmation: boolean | null;
  delivery_gate_allows_write: boolean | null;
  proposed_operation: string | null;
  proposed_commit_message: string | null;
  changed_files_count: number | null;
  changed_files: string[];
  satisfied_conditions: string[];
  blocking_reasons: string[];
  safety_flags: Record<string, unknown>;
  evidence_snapshot_event: string;
  evidence_snapshot_log_path: string;
  evidence_snapshot_schema_version: string | null;
  evidence_snapshot_source: string | null;
};

export type WorkerSlot = {
  slot_id: number;
  state: string;
  worker_name: string | null;
  task_id: string | null;
  task_title: string | null;
  run_id: string | null;
  acquired_at: string | null;
  last_task_id: string | null;
  last_task_title: string | null;
  last_run_id: string | null;
  last_released_at: string | null;
};

export type WorkerSlotSnapshot = {
  max_concurrent_workers: number;
  running_slots: number;
  idle_slots: number;
  slots: WorkerSlot[];
};

export type WorkerPoolRunResponse = {
  requested_workers: number;
  launched_workers: number;
  claimed_runs: number;
  idle_workers: number;
  results: WorkerRunOnceResponse[];
  slot_snapshot: WorkerSlotSnapshot;
};

export type TaskRetryResponse = {
  message: string;
  task_id: string;
  task_title: string;
  previous_status: string;
  current_status: string;
  updated_at: string;
};

export type TaskStateActionResponse = {
  message: string;
  task_id: string;
  task_title: string;
  previous_status: string;
  current_status: string;
  human_status: string;
  paused_reason: string | null;
  updated_at: string;
};
