"""BCG-08A live evidence: generate a real AI summary for a provider run.

This script uses the existing run AI summary API against the BCG-05B
provider-reported Worker run.  It intentionally calls the real provider through
the existing summary regenerate path and fails if the result falls back to the
rule engine.

It never prints or writes an API key.
"""

from __future__ import annotations

import json
from pathlib import Path
import sys
from typing import Any

from fastapi.testclient import TestClient

ORCHESTRATOR_ROOT = Path(__file__).resolve().parents[1]
if str(ORCHESTRATOR_ROOT) not in sys.path:
    sys.path.insert(0, str(ORCHESTRATOR_ROOT))

from app.main import app


TASK_ID = "db204e31-f244-4f9b-a469-abcc5e0b873f"
RUN_ID = "834b38aa-3669-4121-9424-3aa4999cad2e"
EXPECTED_PROVIDER_KEY = "deepseek"
EXPECTED_MODEL_NAME = "deepseek-v4-pro"
EXPECTED_TOKEN_ACCOUNTING_MODE = "provider_reported"
EXPECTED_RUN_PROVIDER_RECEIPT_ID = "3d8bf6e7-fdfd-43db-bd9a-3abee685521d"
EXPECTED_EXECUTION_MODE = "provider_openai"

REQUIRED_SUMMARY_HEADINGS = [
    "## 运行结论",
    "## 已完成内容",
    "## 风险与注意事项",
    "## 下一步建议",
    "## 技术依据",
]


def _assert(condition: bool, message: str) -> None:
    """Raise a concise assertion error for smoke-script failures."""

    if not condition:
        raise AssertionError(message)


def _request_json(
    client: TestClient,
    method: str,
    path: str,
    *,
    expected_status: int = 200,
) -> Any:
    """Call one API path and return JSON, failing loudly on unexpected status."""

    response = client.request(method, path)
    _assert(
        response.status_code == expected_status,
        f"{method} {path} failed: {response.status_code} {response.text[:300]}",
    )
    return response.json()


def _summarize_markdown(markdown: str) -> str:
    """Return a short one-line summary without dumping full AI content."""

    lines = [
        line.strip()
        for line in markdown.splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]
    return " ".join(lines)[:500]


def main() -> None:
    """Generate and verify one source=ai run summary from the existing APIs."""

    with TestClient(app) as client:
        task_runs = _request_json(client, "GET", f"/tasks/{TASK_ID}/runs")
        matching_runs = [item for item in task_runs if item["id"] == RUN_ID]
        _assert(len(matching_runs) == 1, "Expected provider run not found under task.")
        run = matching_runs[0]

        _assert(run["provider_key"] == EXPECTED_PROVIDER_KEY, "provider_key mismatch.")
        _assert(run["model_name"] == EXPECTED_MODEL_NAME, "model_name mismatch.")
        _assert(
            run["token_accounting_mode"] == EXPECTED_TOKEN_ACCOUNTING_MODE,
            "target run is not provider_reported.",
        )
        _assert(run["provider_receipt_id"], "target run is missing provider receipt.")
        _assert(
            run["provider_receipt_id"] == EXPECTED_RUN_PROVIDER_RECEIPT_ID,
            "target run provider receipt mismatch.",
        )
        _assert(run["total_tokens"] > 0, "target run has no provider token evidence.")
        _assert(run["estimated_cost"] > 0, "target run has no cost evidence.")
        _assert(run["log_path"], "target run has no log_path evidence.")
        _assert(run["quality_gate_passed"] is True, "target run quality gate did not pass.")

        generated = _request_json(
            client,
            "POST",
            f"/runs/{RUN_ID}/ai-summary/regenerate",
            expected_status=201,
        )
        current = _request_json(client, "GET", f"/runs/{RUN_ID}/ai-summary")
        history = _request_json(client, "GET", f"/runs/{RUN_ID}/ai-summaries")

    _assert(generated["run_id"] == RUN_ID, "summary run_id mismatch.")
    _assert(generated["task_id"] == TASK_ID, "summary task_id mismatch.")
    _assert(generated["status"] == "succeeded", "summary did not succeed.")
    _assert(generated["source"] == "ai", "summary source is not ai.")
    _assert(
        generated["source"] != "rule_fallback",
        "summary fell back to rule_fallback.",
    )
    _assert(generated["model_provider"] == EXPECTED_PROVIDER_KEY, "summary provider mismatch.")
    _assert(
        generated["model_provider"] != "local_rule_engine",
        "summary was generated by local_rule_engine.",
    )
    _assert(generated["model_name"] == EXPECTED_MODEL_NAME, "summary model mismatch.")
    _assert(generated["provider_receipt_id"], "summary provider receipt missing.")
    _assert(generated["error_summary"] is None, "summary fell back or recorded an error.")
    _assert(generated["stale"] is False, "generated summary should be active.")
    _assert(generated["source_fingerprint"], "summary source_fingerprint missing.")
    _assert(generated["source_hash"], "summary source_hash missing.")
    _assert(generated["prompt_hash"], "summary prompt_hash missing.")

    markdown = generated["summary_markdown"]
    for heading in REQUIRED_SUMMARY_HEADINGS:
        _assert(heading in markdown, f"summary missing heading: {heading}")
    _assert(EXPECTED_PROVIDER_KEY in markdown, "summary does not mention provider_key evidence.")
    _assert(EXPECTED_MODEL_NAME in markdown, "summary does not mention model_name evidence.")
    _assert(
        EXPECTED_RUN_PROVIDER_RECEIPT_ID in markdown,
        "summary does not mention the original provider run receipt.",
    )
    _assert(
        EXPECTED_EXECUTION_MODE in markdown,
        "summary does not mention provider execution mode evidence.",
    )
    _assert(
        EXPECTED_TOKEN_ACCOUNTING_MODE in markdown,
        "summary does not mention provider_reported token accounting evidence.",
    )
    _assert(
        str(run["total_tokens"]) in markdown,
        "summary does not mention total token evidence.",
    )
    _assert(
        str(run["estimated_cost"]) in markdown,
        "summary does not mention estimated cost evidence.",
    )
    _assert(
        run["log_path"] in markdown,
        "summary does not mention log_path evidence.",
    )
    _assert(
        "质量" in markdown and ("通过" in markdown or "pass" in markdown.lower()),
        "summary does not mention quality gate evidence.",
    )

    active_summary = current["active_summary"]
    _assert(active_summary is not None, "current summary is missing.")
    _assert(active_summary["id"] == generated["id"], "current summary is not generated summary.")
    _assert(active_summary["source"] == "ai", "current summary source is not ai.")

    summaries = history["summaries"]
    _assert(
        any(item["id"] == generated["id"] for item in summaries),
        "generated summary is missing from history.",
    )
    _assert(
        history["active_summary"]["id"] == generated["id"],
        "history active_summary does not point at generated summary.",
    )

    report = {
        "phase": "BCG-08A-R1 Real AI Run Summary Evidence Closure",
        "summary_api": {
            "generate": f"POST /runs/{RUN_ID}/ai-summary/regenerate",
            "read_current": f"GET /runs/{RUN_ID}/ai-summary",
            "read_history": f"GET /runs/{RUN_ID}/ai-summaries",
        },
        "real_model_called": True,
        "target_run": {
            "run_id": RUN_ID,
            "task_id": TASK_ID,
            "provider_key": run["provider_key"],
            "model_name": run["model_name"],
            "token_accounting_mode": run["token_accounting_mode"],
            "run_provider_receipt_id": run["provider_receipt_id"],
            "prompt_tokens": run["prompt_tokens"],
            "completion_tokens": run["completion_tokens"],
            "total_tokens": run["total_tokens"],
            "estimated_cost": run["estimated_cost"],
            "quality_gate_passed": run["quality_gate_passed"],
            "log_path": run["log_path"],
        },
        "summary": {
            "summary_id": generated["id"],
            "status": generated["status"],
            "source": generated["source"],
            "model_provider": generated["model_provider"],
            "model_name": generated["model_name"],
            "provider_receipt_id": generated["provider_receipt_id"],
            "error_summary": generated["error_summary"],
            "stale": generated["stale"],
            "source_version": generated["source_version"],
            "source_fingerprint": generated["source_fingerprint"],
            "source_hash": generated["source_hash"],
            "prompt_hash": generated["prompt_hash"],
            "markdown_length": len(markdown),
            "content_excerpt": _summarize_markdown(markdown),
            "fallback_used": False,
            "evidence_coverage": {
                "provider_key": EXPECTED_PROVIDER_KEY in markdown,
                "model_name": EXPECTED_MODEL_NAME in markdown,
                "original_run_receipt": EXPECTED_RUN_PROVIDER_RECEIPT_ID in markdown,
                "execution_mode": EXPECTED_EXECUTION_MODE in markdown,
                "token_accounting_mode": EXPECTED_TOKEN_ACCOUNTING_MODE in markdown,
                "total_tokens": str(run["total_tokens"]) in markdown,
                "estimated_cost": str(run["estimated_cost"]) in markdown,
                "log_path": run["log_path"] in markdown,
                "quality_gate": (
                    "质量" in markdown and ("通过" in markdown or "pass" in markdown.lower())
                ),
            },
        },
        "persistence": {
            "current_active_summary_id": active_summary["id"],
            "history_active_summary_id": history["active_summary_id"],
            "history_count": len(summaries),
            "generated_summary_in_history": True,
        },
    }
    print(json.dumps(report, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
