"""AI Project Director session domain model."""

from datetime import datetime
from enum import StrEnum
from uuid import UUID, uuid4

from pydantic import Field

from app.domain._base import DomainModel


class ProjectDirectorSessionStatus(StrEnum):
    """Project Director session lifecycle."""

    DRAFT = "draft"
    CLARIFYING = "clarifying"
    READY_TO_CONFIRM = "ready_to_confirm"
    CONFIRMED = "confirmed"


class ClarifyingQuestion(DomainModel):
    """A single clarifying question generated by the director."""

    id: str = Field(default_factory=lambda: f"q_{uuid4().hex[:8]}")
    question: str = Field(min_length=1, max_length=500)
    hint: str = Field(default="", max_length=200)
    required: bool = Field(default=True)


class ClarifyingAnswer(DomainModel):
    """User answer to a clarifying question."""

    question_id: str
    answer: str = Field(min_length=1, max_length=2000)


class ProjectDirectorSession(DomainModel):
    """AI Project Director top-level session.

    Tracks the goal intake → clarification → confirmation flow.
    Does NOT replace AgentSession (execution-level) or planning/tasks.
    """

    id: UUID = Field(default_factory=uuid4)
    project_id: UUID | None = None
    goal_text: str = Field(min_length=1, max_length=5000)
    constraints: str = Field(default="", max_length=3000)
    status: ProjectDirectorSessionStatus = Field(
        default=ProjectDirectorSessionStatus.DRAFT
    )
    clarifying_questions: list[ClarifyingQuestion] = Field(default_factory=list)
    clarifying_answers: list[ClarifyingAnswer] = Field(default_factory=list)
    goal_summary: str = Field(default="", max_length=5000)
    confirmed_at: datetime | None = None
    created_at: datetime = Field(default_factory=lambda: datetime.now())
    updated_at: datetime = Field(default_factory=lambda: datetime.now())
